#!/usr/bin/env bash
# This configures HAProxy load balancer

# This updates the package list
sudo apt-get -y update

#This installs the required packages
sudo apt-get -y install software-properties-common

sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 528700-web-01 52.90.0.78:80 check
    server 528700-web-02 3.85.196.138:80 check
"
# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start
