#!/usr/bin/env bash
# This script prints Best School 10 times and prints bad luck for 4 and good luck for 8

i=1
while [ $i -le 10 ]; do
	if [ $i == 4 ]; then
		echo bad luck
	elif [ $i == 8 ]; then
		echo good luck
	else
		echo Best School
	fi
	((i += 1))
done
