#!/usr/bin/env bash
# Updates & Installs ufw firewall & set requirements
sudo apt-get update
sudo apt-get install ufw

# Sets default policies
sudo ufw default deny incoming

# Allows specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW to start enforcing these rules
sudo ufw enable

# check the status
sudo ufw status
