#!/usr/bin/env bash
# Stop Nginx if it's running
sudo service nginx stop

# Modify the nginx configuration file to run as nginx user
# and listen on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2

# Start nginx
sudo service nginx start
